# Gem-specific rubocop config

inherit_from:
  - .rubocop_common.yml
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6


# - Metrics Cops --------------------------------------------------------------

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - '*.gemspec'
